// ============================================================================
// LOCALIZATION — source-of-truth key catalogue + English defaults.
//
// English is authoritative IN CODE (this file). Every user-facing string the
// client shows should have a stable dotted key here. The store seeds any NEW
// keys into the translations table on boot (seed-new-only: existing rows and
// their human/AI translations are never clobbered), so you can grow this
// catalogue incrementally as screens are extracted.
//
// Other languages (pt-BR, es-MX) are filled by admins in the Localization tab
// and/or the AI auto-translate seed; they fall back to the English default here
// whenever a translation is blank.
//
// Casing note: many labels are shown ALL-CAPS by the UI (CSS text-transform on
// .tag/.btn, or an inline transform / .toUpperCase() in the component). Values
// here are stored in natural case so translators get clean source text — the
// component applies the uppercase styling.
// ============================================================================

// The supported locales. `en` is the default/source; the rest are translatable.
// `code` is what the client stores + requests; `label` is shown in pickers.
export const LOCALES = [
  { code: "en", label: "English", flag: "US", source: true },
  { code: "pt-BR", label: "Português (Brasil)", flag: "BR" },
  { code: "es-MX", label: "Español (México)", flag: "MX" },
];
export const DEFAULT_LOCALE = "en";
export const LOCALE_CODES = LOCALES.map((l) => l.code);
export const TRANSLATABLE_LOCALES = LOCALES.filter((l) => !l.source).map((l) => l.code);
export function isLocale(code) {
  return LOCALE_CODES.includes(code);
}

// The English catalogue. Keys are grouped by dotted namespace for readability;
// the object is flat (key -> English string). Keep keys stable — renaming a key
// orphans its translations. Add new keys freely.
export const STRINGS = {
  // ----- common actions / words reused everywhere -----
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.back": "Back",
  "common.confirm": "Confirm",
  "common.delete": "Delete",
  "common.remove": "Remove",
  "common.loading": "Loading…",
  "common.saving": "Saving…",
  "common.retry": "Retry",
  "common.yes": "Yes",
  "common.no": "No",
  "common.search": "Search",
  "common.equip": "Equip",
  "common.equipped": "Equipped",
  "common.buy": "Buy",
  "common.owned": "Owned",

  // ----- navigation rail -----
  "nav.play": "Play",
  "nav.hangar": "Garage",
  "nav.news": "News",
  "nav.perks": "Perks",
  "nav.locker": "Beach Bag",
  "nav.shop": "Shop",
  "nav.wheels": "Wheels",
  "nav.settings": "Options",
  "nav.admin": "Admin",
  "nav.profile": "View profile",
  "nav.signOut": "Sign out",

  // ----- sign-in -----
  "signin.tagline": "3-Minute Beach Kart Mayhem",
  "signin.saddleUp": "Let's roll",
  "signin.googleNotConfigured": "Google sign-in isn't configured on this server yet. It's the only way to log in.",
  "signin.orDev": "— or roll in (dev) —",
  "signin.callSign": "Racer name",
  "signin.rideIn": "Roll in",
  "signin.saddlingUp": "Rolling in…",
  "signin.devHint": "Dev only — any racer name works. Disabled in production.",
  "signin.saveProgress": "Sign in with Google to save your progress across devices.",
  "signin.errDev": "Dev sign-in failed.",
  "signin.errGoogle": "Google sign-in failed.",
  "signin.errReach": "Couldn't reach the sign-in service. Try again shortly.",

  // ----- onboarding (ToS + name) -----
  "onboarding.langTitle": "Choose your language",
  "onboarding.langTag": "Language",
  "onboarding.langIntro": "Pick the language you'd like to play in. You can change it anytime in Options → General.",
  "onboarding.tosTitle": "Before you hit the sand",
  "onboarding.nameTitle": "Name your racer",
  "onboarding.tosTag": "Terms of Service",
  "onboarding.tosIntro": "Welcome to the beach, racer. By rolling into SANDBOX GP you agree to play fair and keep the sand fun for everyone:",
  "onboarding.tosBullet1": "Be respectful. No harassment, hate speech, threats, or abuse toward other players.",
  "onboarding.tosBullet2": "No cheating, exploiting, or disrupting matches for others.",
  "onboarding.tosBullet3": "Keep names and chat appropriate — offensive content is filtered and may be removed.",
  "onboarding.tosBullet4": "You're responsible for activity on your account.",
  "onboarding.tosBullet5": "Accounts that break these rules may be silenced or banned.",
  "onboarding.tosOnce": "You only need to accept these once.",
  "onboarding.agree": "I Agree — Continue",
  "onboarding.recording": "Recording…",
  "onboarding.nameTag": "Choose a racer name",
  "onboarding.nameIntro": "This is the name other racers will see. Letters, numbers, spaces, and . _ - only.",
  "onboarding.namePlaceholder": "e.g. Sandy",
  "onboarding.rideOut": "Hit the Beach",
  "onboarding.errEnterName": "Enter a racer name.",
  "onboarding.errName": "That name couldn't be used.",
  "onboarding.errTos": "Couldn't record acceptance.",

  // ----- settings / options -----
  "settings.kicker": "Config",
  "settings.title": "Options",
  "settings.saving": "Saving…",
  "settings.saved": "Saved",
  "settings.loading": "Loading options…",
  "settings.language": "Language",
  "settings.languageHint": "Changes the interface language.",
  // section rail + category headers
  "settings.sec.general": "General",
  "settings.sec.account": "Account",
  "settings.sec.audio": "Audio",
  "settings.sec.graphics": "Graphics",
  "settings.sec.accessibility": "Accessibility",
  "settings.sec.controls": "Controls",
  // audio
  "settings.audio.master": "Master Volume",
  "settings.audio.music": "Music",
  "settings.audio.sfx": "Sound Effects",
  "settings.audio.voiceVol": "Voice Chat Volume",
  "settings.audio.voiceEnabled": "Voice Chat Enabled",
  "settings.audio.micEnabled": "Microphone Enabled",
  "settings.audio.pushToTalk": "Push To Talk",
  "settings.comingSoon": "Coming soon",
  // graphics
  "settings.gfx.quality": "Quality",
  "settings.gfx.fullscreen": "Fullscreen",
  "settings.gfx.fpsLimit": "FPS Limit",
  "settings.gfx.uncapped": "Uncapped",
  "settings.gfx.screenShake": "Screen Shake",
  // accessibility
  "settings.a11y.colorblind": "Colorblind ID Shapes",
  "settings.a11y.highContrast": "High Contrast",
  "settings.a11y.captions": "Captions",
  "settings.a11y.captionSize": "Caption Size",
  "settings.a11y.reducedMotion": "Reduced Motion",
  "settings.a11y.holdToConfirm": "Hold To Confirm Risky Actions",
  "settings.a11y.showTips": "Show Gameplay Tips",
  "settings.a11y.showControlHints": "Show On-Screen Control Hints",
  // controls
  "settings.controls.hint": "Click a binding, then press a key.",
  "settings.controls.press": "Press a key…",
  // account panel
  "settings.acct.callSign": "Call Sign",
  "settings.acct.changeName": "Change Name",
  "settings.acct.credit": "credit",
  "settings.acct.credits": "credits",
  "settings.acct.newCallSign": "New call sign",
  "settings.acct.apply": "Apply",
  "settings.acct.spendHint": "Spends one credit. The name filter still applies.",
  "settings.acct.noCredits": "You have no name-change credits.",
  "settings.acct.buyInShop": "Buy in shop",
  "settings.acct.nameChanged": "Name changed.",
  "settings.acct.errName": "Could not change name.",
  "settings.acct.streamerMode": "Streamer Mode",
  "settings.acct.streamerHint": "Hides your real name from other players in matches and shows a decoy join code on your lobby. Your real code still works through friend invites.",
  "settings.acct.errStreamer": "Could not update streamer mode.",

  // ----- news (Frontier Dispatch) -----
  "news.kicker": "News",
  "news.title": "Beach Bulletin",
  "news.intro": "The latest from race control. Fresh bulletins wear a NEW mark until you read them — click any bulletin to open the full story.",
  "news.new": "New",
  "news.loading": "Loading bulletins…",
  "news.emptyTitle": "No bulletins",
  "news.emptyBody": "All quiet on the boardwalk. Check back soon.",
  "news.untitled": "Untitled",
  "news.noDetails": "No further details.",

  // ===== T007 extraction blocks — each subagent adds keys ONLY inside its own
  // marked section below (unique anchors avoid edit collisions). Keep natural
  // case; the component applies any uppercase styling. =====

  // ----- shop -----
  // (shop keys go here)
  "shop.equipped": "Equipped!",
  "shop.cantEquip": "Can't equip that yet.",
  "shop.flash.acquired": "Acquired",
  "shop.acquiredSub": "{name} acquired",
  "shop.goldAddedToast": "+{n} Shells added",
  "shop.notEnoughGold": "Not enough Shells.",
  "shop.notEnoughSilver": "Not enough Sea Glass.",
  "shop.alreadyClaimed": "Already claimed.",
  "shop.flash.reward": "Reward",
  "shop.claimedSub": "{name} claimed",
  "shop.watchAd.tag": "Free Sea Glass",
  "shop.watchAd.title": "Watch & Earn",
  "shop.watchAd.desc": "Watch a short ad for {n} Sea Glass. Up to {cap} a day.",
  "shop.watchAd.cta": "Watch Ad · +{n}",
  "shop.watchAd.remaining": "{n} of {cap} left today",
  "shop.watchAd.soldOut": "Daily limit reached — come back tomorrow.",
  "shop.watchAd.claimed": "+{n} Sea Glass",
  "shop.watchAd.failed": "Ad not finished — no reward.",
  "shop.ad.label": "Advertisement",
  "shop.ad.sample": "Your ad here",
  "shop.ad.skipIn": "Reward in {n}s",
  "shop.ad.claim": "Collecting reward…",
  "shop.ad.close": "Close",
  "shop.title": "Shop",
  "shop.silverNuggets": "Sea Glass",
  "shop.goldNuggets": "Shells",
  "shop.tab.silverStore": "Sea Glass Store",
  "shop.tab.goldStore": "Shell Store",
  "shop.tab.lootBoxes": "Beach Chests",
  "shop.tab.loyalty": "Boardwalk",
  "shop.tryingOn": "Trying on",
  "shop.yourRider": "Your racer",
  "shop.hoverToTry": "Hover an item to try it on",
  "shop.testMode": "Test mode",
  "shop.testModeDesc": "Buy Shells with real money (Stripe test mode — no card is charged), then spend them on items below. 1 Shell = $1.",
  "shop.buyGoldNuggets": "Buy Shells",
  "shop.goldStoreSpend": "Shell Store · spend your dollars",
  "shop.gold": "Shells",
  "shop.silver": "Sea Glass",
  "shop.owned": "Owned",
  "shop.buyPrice": "Buy {price}",
  "shop.opening": "Opening…",
  "shop.open": "Open ·",
  "shop.reveal.opened": "Opened",
  "shop.reveal.reward": "Reward",
  "shop.reveal.purchased": "Purchased",
  "shop.duplicate": "Duplicate — converted to spares.",
  "shop.equip": "Equip",
  "shop.nice": "Nice",
  "shop.loading": "Loading…",
  "shop.frontierLoyalty": "Boardwalk Loyalty",
  "shop.loyaltyDesc": "Every Shell you buy builds your boardwalk. Reach a milestone to claim Golden Hour time and an exclusive cosmetic sold nowhere else.",
  "shop.lifetimeOnTrail": "Lifetime on the boardwalk",
  "shop.next": "Next ·",
  "shop.toGo": "{amount} to go",
  "shop.trailBlazed": "Boardwalk built",
  "shop.inactivityReset": "Your boardwalk cooled — progress toward the next milestone reset after {days} days without a purchase. Claimed rewards are always kept.",
  "shop.milestones": "Milestones",
  "shop.amountSpent": "{amount} spent",
  "shop.exclusiveCosmetic": "Exclusive cosmetic",
  "shop.goldTrailBonus": "+ {duration} Golden Hour",
  "shop.claimedCheck": "Claimed ✓",
  "shop.claim": "Claim",
  "shop.amountMore": "{amount} more",
  "shop.durationDay": "{n} Day",
  "shop.durationDays": "{n} Days",
  "shop.durationHour": "{n} Hour",
  "shop.durationHours": "{n} Hours",

  // ----- profile -----
  // (profile keys go here)
  "profile.tab.overview": "Overview",
  "profile.tab.friends": "Friends",
  "profile.tab.achievements": "Achievements",
  "profile.tab.appearance": "Appearance",
  "profile.tab.rankings": "Rankings",
  "profile.riderDossier": "Racer card",
  "profile.levelLine": "LV {level} · {unlocked}/{total} achievements",
  "profile.stat.matches": "Matches",
  "profile.stat.wins": "Wins",
  "profile.stat.winRate": "Win rate",
  "profile.stat.karma": "Karma",
  "profile.overview.bestStreak": "Best Streak",
  "profile.overview.currentStreak": "Current Streak",
  "profile.overview.last10": "Last 10 races",
  "profile.overview.noMatches": "No races logged yet — drop into a race to start your record.",
  "profile.history.win": "Win",
  "profile.history.loss": "Loss",
  "profile.history.tasks": "Tasks",
  "profile.history.tasksShort": "T {n}",
  "profile.history.hide": "Hide",
  "profile.time.justNow": "just now",
  "profile.time.minutesAgo": "{m}m ago",
  "profile.time.hoursAgo": "{h}h ago",
  "profile.time.daysAgo": "{d}d ago",
  "profile.friends.loading": "Loading friends…",
  "profile.friends.empty": "No friends yet — add racers from your match history or the post-race screen.",
  "profile.friends.inLobby": "In lobby",
  "profile.friends.online": "Online",
  "profile.friends.offline": "Offline",
  "profile.friends.mutual": "Mutual",
  "profile.friends.joining": "Joining…",
  "profile.friends.joinLobby": "Join lobby",
  "profile.friends.remove": "Remove",
  "profile.ach.unlocked": "Unlocked",
  "profile.appearance.avatar": "Avatar",
  "profile.appearance.border": "Border",
  "profile.appearance.locked": "{name} — locked",
  "profile.appearance.lock": "Lock",
  "profile.rankings.loading": "Loading board…",
  "profile.rankings.weekly": "Weekly win-rate · resets each week · {week}",
  "profile.rankings.needOne": "{n} more lifetime race to qualify",
  "profile.rankings.needMany": "{n} more lifetime races to qualify",
  "profile.rankings.empty": "No qualified racers yet this week (need ≥{n} lifetime races).",
  "profile.rankings.you": " (you)",
  "profile.rankings.winsRecord": "{wins}W / {matches}",
  "profile.loading": "Loading…",

  // ----- wheels (hover pads) -----
  // (wheels keys go here)
  "wheels.tab.comms": "Comms Wheel",
  "wheels.tab.emote": "Emote Wheel",
  "wheels.holdHint": "In-match: hold {key} to open this wheel, flick to a slot.",
  "wheels.emotePreviewHint": "Click an emote to preview · ~3s movement",
  "wheels.voiceCommands": "Voice Commands",
  "wheels.yourEmotes": "Your Emotes",
  "wheels.emoteSelectHint": "Click an emote to preview it · select a wheel slot to bind.",
  "wheels.emoteBindSlot": "Click an emote to bind it to slot {n}.",
  "wheels.commsSelectHint": "Select a wheel slot, then assign.",
  "wheels.assigningSlot": "Assigning to slot {n}.",
  "wheels.noEmotes": "No emotes owned yet — unlock them by leveling or in the Shop.",
  "wheels.noCommands": "No commands.",
  "wheels.bound": "Bound",
  "wheels.clearSlot": "Clear slot {n}",
  "wheels.hold": "Hold",
  "wheels.slotN": "slot {n}",
  "wheels.cmd.SOS": "Help!",
  "wheels.cmd.HELP_TASK": "Nice one!",
  "wheels.cmd.SABOTAGE_HERE": "Watch out!",
  "wheels.cmd.REFILL_HERE": "Water incoming!",
  "wheels.cmd.FOLLOW_ME": "Follow me!",
  "wheels.cmd.SUSPECT": "Oops!",
  "wheels.cmd.CLEAR": "Good luck!",
  "wheels.cmd.ON_MY_WAY": "On my way!",
  "wheels.cmd.YES": "Yes",
  "wheels.cmd.NO": "No",

  // ----- locker -----
  // (locker keys go here)
  "locker.tryingOn": "Trying on",
  "locker.loadout": "Loadout",
  "locker.hoverHint": "Hover an item to try it on",
  "locker.id": "ID",
  "locker.idTitle": "Carries your ID color",
  "locker.stash": "Beach Bag",
  "locker.use": "Use",
  "locker.unlocksAtLevel": "Unlocks at level {n}",
  "locker.hiddenByCostume": "Hidden by your body costume",
  "locker.reachLevelSlot": "Reach level {n} to equip this slot.",
  "locker.hiddenUnequip": "Hidden by your body costume — unequip the Costume to use this slot.",
  "locker.alwaysWorn": "Always worn · carries your per-match ID color.",
  "locker.unequip": "Unequip",
  "locker.none": "(None)",
  "locker.equipped": "Equipped",
  "locker.source.level": "Level reward",
  "locker.source.box": "Loot box",
  "locker.source.starter": "Starter",
  "locker.source.code": "Code",
  "locker.source.locked": "Locked",

  // ----- hangar (depot) -----
  // (hangar keys go here)
  "hangar.riderDossier": "Racer card",
  "hangar.ranks": "Ranks",
  "hangar.rank": "Rank",
  "hangar.xpBanked": "{xp} XP banked",
  "hangar.lvLevel": "Lv {level}",
  "hangar.xpToLv": "{xp} XP to Lv {next}",
  "hangar.unlockPath": "Unlock path",
  "hangar.newGear": "New gear",
  "hangar.slotGrant": "+ {s} slot",
  "hangar.next": "Next",
  "hangar.loading": "Loading…",

  // ----- perks -----
  // (perks keys go here)
  "perks.kicker": "Perks",
  "perks.title": "Perk arsenal",
  "perks.intro": "Perks unlock as you level up and feed the shared {b}draft pool{/b} your posse votes on before each match. The top three voted perks apply to the whole run — crew perks buff the crew, impostor perks buff the impostor, and the mixed draft never reveals who's who.",
  "perks.unlockedCount": "{open}/{total} unlocked · Level {level}",
  "perks.unlocked": "Unlocked",
  "perks.lockedLv": "🔒 Lv {level}",
  "perks.reachLevel": "Reach level {level} to add this to your draft pool.",

  // ----- play (lobby + in-match HUD) -----
  // (play keys go here)
  "play.ability.dash": "Dash",
  "play.ability.shield": "Shield",
  "play.ability.sabotage": "Sabotage",
  "play.ability.active": "Active {n}s",
  "play.ability.ready": "Ready",
  "play.countdown.draw": "Draw",
  "play.countdown.drawExcl": "Draw!",
  "play.countdown.standBy": "Stand by",
  "play.flash.ejected": "Ejected",
  "play.flash.riderEjected": "Rider ejected",
  "play.flash.crewPrevail": "Crew prevail",
  "play.flash.impostorsWin": "Impostors win",
  "play.flash.victory": "Victory",
  "play.flash.defeat": "Defeat",
  "play.lobby.deploy": "Race",
  "play.lobby.fleetLinkEstablished": "Race link established",
  "play.lobby.connectingToFleet": "Connecting to the beach…",
  "play.lobby.hostMatch": "Host Match",
  "play.lobby.hostMatchDesc": "Create a race & get a join code",
  "play.lobby.joinRandom": "Join Random",
  "play.lobby.joinRandomDesc": "Drop into an open public race — or host one if none are open",
  "play.lobby.joinByCode": "Join by code",
  "play.lobby.join": "Join",
  "play.joke.title": "Nice try",
  "play.joke.subtitle": "Stream sniper detected",
  "play.joke.body": "That code is a decoy a streamer put up to keep their lobby safe. There's no room here — just this screen and your guilty conscience. Ask your friend for a real invite instead.",
  "play.joke.back": "Back to Race",
  "play.invite.title": "Invite a friend",
  "play.invite.loading": "Loading…",
  "play.invite.noFriends": "No friends yet — add racers after a race.",
  "play.invite.invited": "✓ Invited",
  "play.invite.invite": "Invite",
  "play.lobby.mainMenuTitle": "Leave lobby and return to the main menu",
  "play.lobby.mainMenu": "Main menu",
  "play.lobby.briefingRoom": "Starting Grid",
  "play.lobby.joinCode": "Join code",
  "play.lobby.shareCode": "Share this code with your crew. {n}/{max} on the grid.",
  "play.lobby.lastRunPerks": "Last race's winning perks",
  "play.lobby.addBot": "Add a bot",
  "play.lobby.botGreenhorn": "Puddle",
  "play.lobby.botRanger": "Splasher",
  "play.lobby.botGunslinger": "Riptide",
  "play.lobby.botDesc": "Puddle - easy · Splasher - standard · Riptide - fast. Bots race for real and use items.",
  "play.lobby.standingBy": "Standing by",
  "play.lobby.publicLobby": "Public lobby",
  "play.lobby.friendsOnly": "Friends only",
  "play.lobby.closeToPublicTitle": "Close to public (friends only)",
  "play.lobby.openToPublicTitle": "Open to public",
  "play.lobby.openDesc": "Open — anyone can drop in via Join Random.",
  "play.lobby.closedDesc": "Closed — only racers with the join code can enter. Toggle on to open to the public.",
  "play.lobby.friendsOnlyLobby": "Friends-only lobby",
  "play.lobby.volunteerTitle": "Secretly raise your odds of drawing the impostor role",
  "play.lobby.volunteeringAsImpostor": "Volunteering as impostor",
  "play.lobby.volunteerAsImpostor": "Volunteer as impostor",
  "play.lobby.volunteerDesc": "Secret — only you can see this. Greatly raises your odds of being the impostor, but it's never guaranteed.",
  "play.lobby.beginDraft": "Begin Perk Draft →",
  "play.lobby.needRider": "Need {n} more racer",
  "play.lobby.needRiders": "Need {n} more racers",
  "play.lobby.waitingForHost": "Waiting for host...",
  "play.lobby.ridersAboard": "racers on the grid",
  "play.lobby.shipLayoutHint": "Sandcastle Circuit ahead — 3 laps, water weapons hot, first across the line wins.",
  "play.draft.leaveTitle": "Leave the draft and return to the main menu",
  "play.draft.leave": "Leave",
  "play.draft.title": "Perk Draft",
  "play.draft.subtitle": "Vote up to 3 — the squad's top picks go live. Drawn from gear your team has unlocked.",
  "play.draft.lockInVotes": "Lock In Votes ({n}/3)",
  "play.hud.crewListTitle": "Racers",
  "play.hud.noOtherRiders": "No other real racers in this race.",
  "play.hud.paused": "Paused",
  "play.hud.resume": "Resume",
  "play.hud.settings": "Settings",
  "play.hud.surrenderAndQuit": "Surrender & Quit",
  "play.hud.abandonTitle": "Leave the race?",
  "play.hud.abandonBody": "The grid will be down a racer. Are you sure you want to quit?",
  "play.hud.surrender": "Surrender",
  "play.hud.pressEscResume": "Press ESC to resume",
  "play.hud.close": "Close",
  "play.hud.rigStatus": "Rig status",
  "play.hud.gaugeArmor": "ARMOR",
  "play.hud.gaugePower": "POWER",
  "play.hud.gaugeBattery": "YOUR BATTERY",
  "play.hud.journey": "Journey",
  "play.hud.journeyToDepot": "{n} / {total} to depot",
  "play.hud.powerBalance": "Power balance",
  "play.hud.pltPct": "PLT {n}%",
  "play.hud.engPct": "ENG {n}%",
  "play.hud.setAtCockpit": "set at the Cockpit",
  "play.hud.incomingAttackWave": "INCOMING ATTACK WAVE",
  "play.hud.manTurretStations": "Man the turret stations immediately!",
  "play.hud.attackWaveInbound": "ATTACK WAVE INBOUND",
  "play.hud.shipsLeftCount": "{n} LEFT",
  "play.hud.manTheCannons": "Man the cannons — shoot them down!",
  "play.hud.youWereDowned": "You were downed",
  "play.hud.enteringEnergyPlane": "Entering energy plane",
  "play.hud.energyPlaneStillInPlay": "Energy plane — still in play",
  "play.hud.energyHint": "Finish energy tasks to help your team. A second shock on this plane ends you for good.",
  "play.hud.spectatingFellOff": "SPECTATING — YOU FELL OFF THE TRAIN",
  "play.hud.spectatingFroze": "SPECTATING — YOU FROZE SOLID",
  "play.hud.spectatorHint": "You're out for good. Comms are offline — use WASD / arrows to roam the camera and watch.",
  "play.hud.downedEnergy": "DOWNED · ENERGY",
  "play.hud.buildTag": "build R27",
  "play.hud.comms": "Comms",
  "play.hud.emote": "Emote",
  "play.hud.ejectVote": "EJECT VOTE",
  "play.hud.voted": "VOTED",
  "play.hud.inCorridor": "In corridor",
  "play.hud.walkOntoMarker": "Walk onto the ❗ marker",
  "play.hud.noTasksHere": "No tasks here",
  "play.hud.freezerOpen": "Freezer open — get out before you freeze!",
  "play.hud.freezerLocked": "Locked in the freezer — battery draining to keep you warm!",
  "play.hud.chargingCannon": "Charging Cannon... {n}s ⚡",
  "play.hud.manTheCannon": "Man the Cannon ☄",
  "play.hud.territoryMap": "Territory map",
  "play.hud.mapCloseHint": "[M] or [Esc] to close",
  "play.hud.activePerksThisRun": "Active perks this run",
  "play.hud.crewPrevailResult": "CREW PREVAIL",
  "play.hud.impostorsWinResult": "IMPOSTORS WIN",
  "play.hud.youWon": "YOU WON",
  "play.hud.youLost": "YOU LOST",
  "play.hud.theVictors": "The Victors",
  "play.hud.theImpostorsWere": "The Impostors Were",
  "play.hud.finalRoster": "Final Roster",
  "play.hud.karmaHint": "Give karma to up to 2 racers you enjoyed playing with. Add friends or report misconduct.",
  "play.hud.missionReport": "Race Report",
  "play.hud.xpEarned": "XP earned",
  "play.hud.xpBase": "50 base",
  "play.hud.xpVictoryBonus": " + 75 victory bonus",
  "play.hud.xpGoldTrail": " · ×1.5 Gold Trail",
  "play.hud.silverNuggets": "Sea Glass",
  "play.hud.rank": "Rank",
  "play.hud.lv": "LV {n}",
  "play.hud.xpAwardedHint": "XP is awarded to your account by the server. Reopen the Garage to see your updated rank.",
  "play.hud.restarting": "Restarting…",
  "play.hud.rematch": "↻ Rematch (same grid)",
  "play.hud.hostMayRematch": "Host may rematch the grid",
  "play.hud.returnToLobby": "Return to Lobby",
  "play.hud.achievementUnlocked": "Achievement unlocked",
  "play.hud.cabThrottle": "Cab throttle",
  "play.hud.platingLabel": "PLATING · slow & safe",
  "play.hud.enginesLabel": "ENGINES · fast & exposed",
  "play.hud.setTarget": "SET (target)",
  "play.hud.pctEngines": "{n}% engines",
  "play.hud.actual": "ACTUAL",
  "play.hud.now": "now",
  "play.hud.pctPlating": "{n}% plating",
  "play.hud.cabThrottleDesc": "Slowing down is quick (~5s); speeding up takes longer (~15s). During a raid, more plating = less armor damage.",
  "play.hud.doneEsc": "Done (ESC)",
  "play.hud.turretGrid": "Turret grid",
  "play.hud.shipsLeftLabel": "{n} SHIPS LEFT",
  "play.hud.currentEngineSpeed": "Current engine speed:",
  "play.hud.shipsFasterHint": "Higher speed = ships disappear faster!",
  "play.hud.closeConsoleEsc": "Close console (ESC)",
  "play.reason.all_impostors_down": "Every impostor was ejected.",
  "play.reason.reached_location": "The crew reached the depot.",
  "play.reason.hull_destroyed": "The train's armor was torn apart.",
  "play.reason.impostors_parity": "The impostors reached parity.",
  "play.reason.sabotage_unresolved": "A sabotage went unresolved.",
  "play.reason.matchEnded": "The match has ended.",

  // ----- hud (in-match shared) -----
  // (hud keys go here)
  "hud.hint.completeMinigame": "Complete the mini-game",
  "hud.hint.cancelTask": "Cancel task",
  "hud.hint.move": "Move",
  "hud.hint.doTask": "Do task: {name}",
  "hud.hint.standOnMarker": "Stand on the ❗ to start the task",
  "hud.hint.rechargeBattery": "Recharge Battery",
  "hud.hint.repairRecharging": "Repair (recharging {s}s)",
  "hud.hint.repairArmor": "Repair armor",
  "hud.hint.walkToStation": "Walk to the station icon",
  "hud.hint.manCannon": "Man cannon — fire!",
  "hud.hint.getToCannon": "Get to the cannon!",
  "hud.hint.droneShock": "Drone shock {name}",
  "hud.hint.droneNoTarget": "Drone: no target in range",
  "hud.hint.stopDriving": "Stop driving (leave drone)",
  "hud.hint.shockCd": "Shock {name} ({s}s)",
  "hud.hint.shock": "Shock {name}",
  "hud.hint.shockRecharging": "Shock recharging ({s}s)",
  "hud.hint.sabotageCd": "Sabotage ({s}s)",
  "hud.hint.sabotage": "Sabotage",
  "hud.hint.recoverDrone": "Recover drone (walk to it)",
  "hud.hint.deployDrone": "Deploy recon drone",
  "hud.hint.dashCd": "Dash ({s}s)",
  "hud.hint.chargeDash": "Charge dash — aim & release",
  "hud.hint.barrierUp": "Barrier up ({s}s)",
  "hud.hint.barrierCd": "Barrier ({s}s)",
  "hud.hint.ironBarrier": "Iron barrier",
  "hud.hint.commsWheel": "Comms wheel",
  "hud.key.holdKey": "Hold {key}",
  "hud.controlsTitle": "Controls",
  "hud.tipTitle": "Tip",
  "hud.confirmHold": "Hold",
  "hud.tip.crew.power": "Chores generate power. Power runs the battery, the engine, and the armor plating.",
  "hud.tip.crew.engineArmor": "Engine running = armor down. Barrel toward the depot, then cut the engine to patch armor.",
  "hud.tip.crew.pairs": "Stay in pairs — a lone crew member is easy to pick off.",
  "hud.tip.crew.energyPlane": "If you're pulled to the energy plane you're still in play. Keep doing tasks.",
  "hud.tip.crew.vote": "Call a vote on anyone you saw acting suspiciously. Majority ejects.",
  "hud.tip.crew.sabotageFuse": "Resolve sabotages fast — some have a fuse that ends the match if it runs out.",
  "hud.tip.imp.shock": "Catch a crew member alone, then F to shock them to the energy plane.",
  "hud.tip.imp.secondShock": "A second shock on the energy plane eliminates them for good.",
  "hud.tip.imp.splitCrew": "Sabotage to split the crew and force them away from tasks.",
  "hud.tip.imp.furnaceFuse": "Furnace Overload has a fuse — if crew can't reach it in time, you win.",
  "hud.tip.imp.blendIn": "Blend in: stand near tasks and move with the group.",
  "hud.reasonRequired": "Please give a reason.",
  "hud.reportFiled": "Report filed. Thank you.",

  // ----- comms (comms wheel) -----
  // (comms keys go here)
  "comms.cmd.SOS": "Help!",
  "comms.cmd.HELP_TASK": "Nice one!",
  "comms.cmd.SABOTAGE_HERE": "Watch out!",
  "comms.cmd.REFILL_HERE": "Water incoming!",
  "comms.cmd.FOLLOW_ME": "Follow me!",
  "comms.cmd.SUSPECT": "Oops!",
  "comms.cmd.CLEAR": "Good luck!",
  "comms.cmd.ON_MY_WAY": "On my way!",
  "comms.cmd.YES": "Yes",
  "comms.cmd.NO": "No",
  "comms.hubComms": "Comms",
  "comms.radialHint": "Click a command · release C to close",
  "comms.hubEmote": "Emote",
  "comms.emoteBindHint": "Bind emotes in the Wheels menu",
  "comms.emoteHint": "Click an emote · release V to close",

  // ----- sabotage -----
  // (sabotage keys go here)
  "sabotage.name.LIFE_SUPPORT": "Air Bellows Down",
  "sabotage.desc.LIFE_SUPPORT": "Refills disabled until fixed.",
  "sabotage.name.REACTOR_MELTDOWN": "Furnace Overload",
  "sabotage.desc.REACTOR_MELTDOWN": "Fix before the fuse or impostors win.",
  "sabotage.name.COMMS_BLACKOUT": "Telegraph Cut",
  "sabotage.desc.COMMS_BLACKOUT": "Telegraph scrambled.",
  "sabotage.name.ATTRACT_ATTACKERS": "Trail Exposed",
  "sabotage.desc.ATTRACT_ATTACKERS": "Raids come faster & harder.",
  "sabotage.name.LIGHTS_OUT": "Lanterns Out",
  "sabotage.desc.LIGHTS_OUT": "Crew sight dimmed.",
  "sabotage.name.EMP_OUTAGE": "Dynamo Blown",
  "sabotage.desc.EMP_OUTAGE": "Task completion frozen.",
  "sabotage.title": "Sabotage",
  "sabotage.cooldown": "Cooldown {s}s",
  "sabotage.alreadyActive": "Already active",
  "sabotage.close": "Close",
  "sabotage.fixAt": "Fix at: {rooms} · {resolved}/{needed} done",
  "sabotage.resolveHere": "Resolve here ({resolved}/{needed})",

  // ----- vote (eject voting) -----
  // (vote keys go here)
  "vote.titleKanji": "Vote",
  "vote.title": "Eject vote",
  "vote.grace": "Grace",
  "vote.votesCast": "Votes cast",
  "vote.majority": "{cast} · Majority {needed}",
  "vote.talliesHidden": "Individual tallies are hidden until an ejection — vote on who you suspect.",
  "vote.crossedOver": "You've crossed over — you can't vote.",
  "vote.rosterYou": "{name} (you)",
  "vote.voted": "Voted",
  "vote.clearMyVote": "Clear my vote",
  "vote.close": "Close",

  // ----- minigame (task minigames) -----
  // (minigame keys go here)
  "minigame.done": "Done",
  "minigame.taskComplete": "Task complete",
  "minigame.ghostTask": "Ghost task",
  "minigame.task": "Task",
  "minigame.completeTask": "Complete the task",
  "minigame.abort": "Abort",
  "minigame.inProgress": "In progress",
  "minigame.label.wire_connect": "Click to rotate pipes and route the power.",
  "minigame.label.code_sequence": "Type the sequence rapidly using WASD.",
  "minigame.label.alignment": "Keep the slider in the moving sweet spot.",
  "minigame.label.hold_timing": "Tap repeatedly to keep the needle stabilized.",
  "minigame.label.flux_route": "Shoot down bandit raiders before they escape!",
  "minigame.label.phase_match": "Keep the slider in the moving sweet spot.",
  "minigame.label.turret_defense": "Shoot down bandit raiders before they damage the train!",
  "minigame.reflexHint": "Type the sequence quickly",
  "minigame.flappyHint": "Click or press space to stabilize",
  "minigame.targetsHit": "{score}/5 targets hit",
};
